f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace("None","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()

f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace("Click here for your comments","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()

f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace("Comment via Facebook","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()


f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace("Don't have facebook account? Use this form to comment ","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()

f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace("Published: 02-07-2016","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()

f = open('hellotxt.csv','r')
filedata = f.read()
f.close()
newdata = filedata.replace(",","")
f = open('hellotxt.csv','w')
f.write(newdata)
f.close()
